### ISSUE TITLE
Tracking: Docs

### ISSUE THREAD

**Issue by sudo-carson** [pykeio/millennium#27]
# High Priority
- [x] Installation
- [x] More examples for more parts of the API
- [ ] Starter app walkthrough
- [ ] CLI & bundler usage

# Medium Priority
- [ ] Complete start-to-finish tutorial for a medium-sized project
- [ ] Electron porting guide
- [ ] Cover more advanced topics
    - [ ] Start-to-finish tutorial for a slightly larger project using more advanced features

# Low Priority
- [ ] In-depth dive into Millennium internals
